### ISSUE TITLE
How to integrate with existing scarb project

### ISSUE THREAD

**Issue by princeibs** [zkLend/zklend-v1-core#79]
Hi, I want to use `market.cairo` contract in my scarb project but scarb is throwing errors when I add this repo URL as a dependency in my `scarb.toml` file.

This is my screenshot of my `scarb.toml`: 
<img width="572" alt="image" src="https://github.com/zkLend/zklend-v1-core/assets/64266194/f96645c2-9c0e-4672-ae73-3ca438b3e546">

This is the error scarb is throwing:
<img width="572" alt="image" src="https://github.com/zkLend/zklend-v1-core/assets/64266194/2c79fcfd-08ad-4508-8140-5026d6fd96f9">

**Comment by xJonathanLEI** [comment]
Hi this is not a Scarb project. We don't use Scarb for development.

**Comment by maciektr** [comment]
Hi @xJonathanLEI! 
Curious to know what is stopping you from migrating to Scarb? I am open to chat about your needs.

**Comment by xJonathanLEI** [comment]
@maciektr We started before Scarb IIRC. That's why :)

Also IIUC Scarb mostly deals with dependency management. We don't have any dependency. That's why we never had a need for that.

But if adding ad manifest makes it easier for people to use this as dependency then yeah we can do that.
