### ISSUE TITLE
Missing Scarb manifest 

### ISSUE THREAD

**Issue by maciektr** [zkLend/zklend-v1-core#80]
Reopening https://github.com/zkLend/zklend-v1-core/issues/79 as I feel this has not been properly addressed yet. 

I am curious to know, what is your reason to avoid using Scarb, or even add a `Scarb.toml` manifest?
Lack of manifest file makes it impossible for community to use this project as a dependency.

**Comment by xJonathanLEI** [comment]
https://github.com/zkLend/zklend-v1-core/issues/79#issuecomment-2179540950
