### ISSUE TITLE
Collateral Balance not being exposed (Liquidations)

### ISSUE THREAD

**Issue by kristiann57** [zkLend/zklend-v1-core#82]
Hi team, 

I am trying to understand and research the liquidation landscape in your protocol, I understand by scanning over your code that you are protecting users from being unfairly liquidated, meaning after each liquidation the user cannot be over_collaterilized, therefore promoting a very competitive MEV ecosystem. 

In order to perform these calculations it is necessary to know the balance of the accumulated debt assets and the balance of the accumulated collateral... however, the current design does not allow to query the collateral balance of a given user, as this information cannot be retrieved by any external getter function. (I would imagine that you could get the balance of the user by querying directly the balanceOf(liquidatableUser) on the zToken contract, but we all know that most users might trade/restake or move those tokens somewhere else )

I could imagine you might be runing your own bot to keep the protocol healthy, am I right to assume that you are querying the storage slot of the smart contract directly in order to get this information?

thanks in advance

**Comment by kristiann57** [comment]
After double-checking the Ztoken contract, I am inclined to believe that the right approach is to query the Ztoken for the balance of the liquidatable user.... would love to hear your feedback
thanks

**Comment by 9oelM** [comment]
@kristiann57 your guess is correct. The zToken balance is equivalent to the collateral balance of the underlying token.

**Comment by kristiann57** [comment]
Thanks for the info ;)
